package jetbrains.buildServer.clouds.ecs;

/**
 * Created by ekoshkin (koshkinev@gmail.com) on 07.06.17.
 */

val AGENT_NAME_ECS_ENV = "TEAMCITY_ECS_AGENT_NAME"
val SERVER_URL_ECS_ENV = "TEAMCITY_ECS_SERVER_URL"
val SERVER_UUID_ECS_ENV = "TEAMCITY_ECS_SERVER_UUID"
val IMAGE_NAME_ECS_ENV = "TEAMCITY_ECS_IMAGE_NAME"
val PROFILE_ID_ECS_ENV = "TEAMCITY_ECS_CLOUD_PROFILE_ID"
val INSTANCE_NAME_ECS_ENV = "TEAMCITY_ECS_INSTANCE_NAME"

val OFFICIAL_IMAGE_SERVER_URL_ECS_ENV = "SERVER_URL";
