

package jetbrains.buildServer.clouds.ecs

/**
 * Created by ekoshkin (koshkinev@gmail.com) on 07.06.17.
 */

const val TEAMCITY_ECS_PREFIX = "TEAMCITY_ECS_"
const val TEAMCITY_ECS_PROVIDED_PREFIX = "TC_ECS_PROVIDED_"

const val SERVER_URL_ECS_ENV = TEAMCITY_ECS_PREFIX + "SERVER_URL"
const val SERVER_UUID_ECS_ENV = TEAMCITY_ECS_PREFIX + "SERVER_UUID"
const val IMAGE_ID_ECS_ENV = TEAMCITY_ECS_PREFIX + "IMAGE_ID"
const val PROFILE_ID_ECS_ENV = TEAMCITY_ECS_PREFIX + "CLOUD_PROFILE_ID"
const val INSTANCE_ID_ECS_ENV = TEAMCITY_ECS_PREFIX + "INSTANCE_ID"
const val STARTING_INSTANCE_ID_ECS_ENV = TEAMCITY_ECS_PREFIX + "STARTING_INSTANCE_ID"
const val AGENT_NAME_ECS_ENV = TEAMCITY_ECS_PREFIX + "AGENT_NAME"

const val OFFICIAL_IMAGE_SERVER_URL_ECS_ENV = "SERVER_URL"
const val ECS_CONTAINER_METADATA_URI = "ECS_CONTAINER_METADATA_URI"
const val ECS_CONTAINER_METADATA_FILE = "ECS_CONTAINER_METADATA_FILE"

const val REQUIRED_PROFILE_ID_CONFIG_PARAM = "system.cloud.profile_id"
const val STARTING_INSTANCE_ID_CONFIG_PARAM = "teamcity.agent.startingInstanceId"