package jetbrains.buildServer.clouds.ecs

/**
 * Created by ekoshkin (koshkinev@gmail.com) on 07.06.17.
 */

const val TEAMCITY_ECS_PREFIX = "TEAMCITY_ECS_"

const val SERVER_URL_ECS_ENV = TEAMCITY_ECS_PREFIX + "SERVER_URL"
const val SERVER_UUID_ECS_ENV = TEAMCITY_ECS_PREFIX + "SERVER_UUID"
const val IMAGE_ID_ECS_ENV = TEAMCITY_ECS_PREFIX + "IMAGE_ID"
const val PROFILE_ID_ECS_ENV = TEAMCITY_ECS_PREFIX + "CLOUD_PROFILE_ID"
const val INSTANCE_ID_ECS_ENV = TEAMCITY_ECS_PREFIX + "INSTANCE_ID"

const val OFFICIAL_IMAGE_SERVER_URL_ECS_ENV = "SERVER_URL"
